# Generated by Django 2.2.5 on 2019-09-22 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0003_images_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=20)),
                ('contact_no', models.IntegerField(blank=True, verbose_name=10)),
                ('image', models.ImageField(blank=True, upload_to='people/', verbose_name='People')),
            ],
        ),
        migrations.RemoveField(
            model_name='members',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='members',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='members',
            name='position',
        ),
        migrations.RemoveField(
            model_name='members',
            name='post',
        ),
        migrations.AddField(
            model_name='members',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='eventapp.Postevent'),
        ),
        migrations.AddField(
            model_name='members',
            name='person',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='eventapp.People'),
        ),
    ]
