# Generated by Django 2.2.5 on 2019-09-22 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0004_auto_20190922_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.Postevent'),
        ),
        migrations.AlterField(
            model_name='members',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.People'),
        ),
    ]
