# Generated by Django 2.2.5 on 2019-09-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0005_auto_20190922_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='postevent',
            name='slug',
            field=models.SlugField(default='duck', unique=True),
        ),
    ]
